name = "mathlib_proofs"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["MathlibProofs"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
# 这不是 mathlib 本体，关掉它的版权头/文档字符串风格检查
weak.linter.mathlibStandardSet = false
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.32.2"

[[lean_lib]]
name = "MathlibProofs"
